name: Create mirror release

on:
  schedule:
    - cron:  "*/15 * * * *"

env:
  SPACEMACS_REPO: syl20bnr/spacemacs
  SPACEMACS_BRANCH: develop
  SPACEMACS_DIR: spacemacs
  MIRROR_SCRIPT: ./create_mirror
  EM_SCRIPT_PATH: $HOME/elpa-mirror.el
  MIRROR_DIR: /tmp/elpa
  MIRROR_NAME: elpa-zip
  RELEASE_NAME: elpamirror
  EM_SCRIPT_URL: "https://raw.githubusercontent.com/\
  redguardtoo/\
  elpa-mirror/\
  master/\
  elpa-mirror.el"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 27.1

    - name: Download elpa-mirror.el
      run: curl -o ${{ env.EM_SCRIPT_PATH }} ${{ env.EM_SCRIPT_URL }}

    - uses: actions/checkout@v2

    - name: checkout Spacemacs repo
      uses: actions/checkout@v2
      with:
        repository: ${{ env.SPACEMACS_REPO }}
        ref: ${{ env.SPACEMACS_BRANCH }}
        path: ${{ env.SPACEMACS_DIR }}

    - name: Create local mirror
      run: ${{ env.MIRROR_SCRIPT }}

    - name: Archive mirror
      run: zip -r -j /tmp/elpa.zip ${{ env.MIRROR_DIR }}

    - name: Create release
      id: create_release
      continue-on-error: true
      uses: actions/create-release@v1
      # Expected to fail if release with the same hash exists
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ hashFiles("/tmp/elpa.zip") }}
        release_name: ${{ env.RELEASE_NAME }}
        body: Spacemacs elpa mirror for testing
        draft: false
        prerelease: false

    - name: Upload Release Asset
      # Expected to fail if create_release faild
      continue-on-error: true
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ hashFiles("/tmp/elpa.zip") }}
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/elpa.zip
        asset_name: ${{ env.MIRROR_NAME }}
        asset_content_type: application/zip
